// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKQm7LSdh_dAKHd7JyaQTrH90tq_roX0',
    appId: '1:166969531699:web:d8fdac521e13d15092f246',
    messagingSenderId: '166969531699',
    projectId: 'ecommerce-app-f4334',
    authDomain: 'ecommerce-app-f4334.firebaseapp.com',
    databaseURL: 'https://ecommerce-app-f4334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-f4334.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjTkXiXaPpwJ4aT-Ns1VLKlKaRVYtaduE',
    appId: '1:166969531699:android:41d141bb3869819492f246',
    messagingSenderId: '166969531699',
    projectId: 'ecommerce-app-f4334',
    databaseURL: 'https://ecommerce-app-f4334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-f4334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9-k2u5sTukzlnqZTJ2z8PNkg6aBEhvc',
    appId: '1:166969531699:ios:46dc89f26453952e92f246',
    messagingSenderId: '166969531699',
    projectId: 'ecommerce-app-f4334',
    databaseURL: 'https://ecommerce-app-f4334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-f4334.appspot.com',
    iosClientId: '166969531699-mrok1gqkpit30jhkd7epha83vvcj8vcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe9-k2u5sTukzlnqZTJ2z8PNkg6aBEhvc',
    appId: '1:166969531699:ios:46dc89f26453952e92f246',
    messagingSenderId: '166969531699',
    projectId: 'ecommerce-app-f4334',
    databaseURL: 'https://ecommerce-app-f4334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-f4334.appspot.com',
    iosClientId: '166969531699-mrok1gqkpit30jhkd7epha83vvcj8vcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
